model_path: "vosk-model-small-ru-0.22"
samplerate: 16000
blocksize: 8000
device: null 
max_workers: 2

question_map:
  map_path: questions_video_map.json
  match_threshold: 0.7

fallback_questions_path: questions_video_map_expanded.json
fallback_threshold: 0.6

video_dir: "videos"
fallback_video: "videos/error.mp4"
